// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ats/analyze': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ats/analyze.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/careers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/careers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/careers/index.post').default>>>>
    }
    '/api/careers/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/careers/search.get').default>>>>
    }
    '/api/humanizer/process': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/humanizer/process.post').default>>>>
    }
    '/api/interviews/:id/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/interviews/[id]/chat.post').default>>>>
    }
    '/api/interviews': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/interviews/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/interviews/index.post').default>>>>
    }
    '/api/qa/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qa/generate.post').default>>>>
    }
    '/api/resumes/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/resumes/[id].get').default>>>>
    }
    '/api/resumes/:id/refine': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/resumes/[id]/refine.post').default>>>>
    }
    '/api/resumes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/resumes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/resumes/index.post').default>>>>
    }
    '/api/resumes/parse': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/resumes/parse.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}