package com.example.chaeklist;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Timestamp;
import java.time.LocalDateTime;

import com.example.chaeklist.domain.readingroom.service.ReadingRoomNotificationScheduler;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;

@SpringBootTest
class ReadingRoomNotificationSchedulerTest {

	@Autowired
	private ReadingRoomNotificationScheduler scheduler;

	@Autowired
	private JdbcTemplate jdbcTemplate;

	@Test
	@Transactional
	void sendsStartAndCheckInNotificationsOnlyOnce() {
		createTables();
		long userId = insertUser("reading-room-notify@chaeklist.kr", "notify-user");
		long disabledUserId = insertUser("reading-room-disabled@chaeklist.kr", "disabled-user");
		long completedUserId = insertUser("reading-room-completed@chaeklist.kr", "completed-user");
		long bookId = insertBook();
		long startRoomId = insertRoom(userId, bookId, "시작 예정 모각독", LocalDateTime.now().plusMinutes(30), LocalDateTime.now().plusMinutes(90));
		long endedRoomId = insertRoom(userId, bookId, "종료된 모각독", LocalDateTime.now().minusMinutes(65), LocalDateTime.now().minusMinutes(5));
		insertParticipant(startRoomId, userId, "JOINED");
		insertParticipant(startRoomId, disabledUserId, "JOINED");
		insertParticipant(endedRoomId, userId, "JOINED");
		insertParticipant(endedRoomId, completedUserId, "CANCELED");
		disableServiceNotifications(disabledUserId);

		scheduler.sendDueNotifications();
		scheduler.sendDueNotifications();

		assertThat(countNotifications(userId, startRoomId)).isEqualTo(1);
		assertThat(countNotifications(userId, endedRoomId)).isEqualTo(1);
		assertThat(countNotifications(disabledUserId, startRoomId)).isZero();
		assertThat(countNotifications(completedUserId, endedRoomId)).isZero();
		assertThat(countEvents(userId, startRoomId, "READING_ROOM_START")).isEqualTo(1);
		assertThat(countEvents(userId, endedRoomId, "READING_ROOM_CHECKIN")).isEqualTo(1);
	}

	private void createTables() {
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS reading_rooms (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					host_user_id BIGINT NOT NULL,
					book_id BIGINT NOT NULL,
					title VARCHAR(100) NOT NULL,
					description VARCHAR(500),
					max_participants INT NOT NULL,
					status VARCHAR(20) NOT NULL DEFAULT 'RECRUITING',
					visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
					idempotency_key VARCHAR(100),
					created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
				)
				""");
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS reading_room_schedules (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					room_id BIGINT NOT NULL,
					day_of_week TINYINT NOT NULL,
					day_label VARCHAR(10) NOT NULL,
					scheduled_time TIME NOT NULL,
					duration_minutes INT NOT NULL,
					created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
				)
				""");
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS reading_room_sessions (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					room_id BIGINT NOT NULL,
					schedule_id BIGINT NOT NULL,
					session_date DATE NOT NULL,
					scheduled_start_at DATETIME(6) NOT NULL,
					scheduled_end_at DATETIME(6) NOT NULL,
					started_at DATETIME(6),
					ended_at DATETIME(6),
					status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
					created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
				)
				""");
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS reading_room_participants (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					room_id BIGINT NOT NULL,
					user_id BIGINT NOT NULL,
					status VARCHAR(20) NOT NULL DEFAULT 'JOINED',
					joined_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
					canceled_at DATETIME(6),
					CONSTRAINT uk_reading_room_participants_room_user UNIQUE (room_id, user_id)
				)
				""");
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS reading_room_admin_hidden (
					room_id BIGINT PRIMARY KEY,
					hidden_by_user_id BIGINT,
					reason VARCHAR(255),
					created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
				)
				""");
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS reading_room_notification_events (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					session_id BIGINT NOT NULL,
					room_id BIGINT NOT NULL,
					user_id BIGINT NOT NULL,
					notification_type VARCHAR(30) NOT NULL,
					created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT uk_reading_room_notification_events_session_user_type UNIQUE (session_id, user_id, notification_type)
				)
				""");
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS user_notification_settings (
					user_id BIGINT PRIMARY KEY,
					like_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
					report_status_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
					service_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
					created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
				)
				""");
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS user_notifications (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					user_id BIGINT NOT NULL,
					notification_type VARCHAR(30) NOT NULL,
					target_type VARCHAR(30) NOT NULL,
					target_id BIGINT NOT NULL,
					title VARCHAR(100) NOT NULL,
					message VARCHAR(255) NOT NULL,
					read_at DATETIME(6),
					created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
				)
				""");
	}

	private long insertUser(String email, String nickname) {
		jdbcTemplate.update("""
				INSERT INTO users (
					email, nickname, password_hash, status, role, onboarding_completed, created_at, updated_at
				)
				VALUES (?, ?, 'hash', 'ACTIVE', 'USER', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
				""", email, nickname);
		return jdbcTemplate.queryForObject("SELECT id FROM users WHERE email = ?", Long.class, email);
	}

	private long insertBook() {
		jdbcTemplate.update("""
				INSERT INTO books (
					title, author, description, is_general_eligible, filter_status, created_at, updated_at
				)
				VALUES ('알림 테스트 책', '테스트 저자', '설명', TRUE, 'INCLUDED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
				""");
		return jdbcTemplate.queryForObject("SELECT MAX(id) FROM books", Long.class);
	}

	private long insertRoom(long hostUserId, long bookId, String title, LocalDateTime startAt, LocalDateTime endAt) {
		jdbcTemplate.update("""
				INSERT INTO reading_rooms (
					host_user_id, book_id, title, max_participants, status, visibility, created_at, updated_at
				)
				VALUES (?, ?, ?, 5, 'RECRUITING', 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
				""",
				hostUserId,
				bookId,
				title);
		long roomId = jdbcTemplate.queryForObject("SELECT MAX(id) FROM reading_rooms", Long.class);
		jdbcTemplate.update("""
				INSERT INTO reading_room_schedules (room_id, day_of_week, day_label, scheduled_time, duration_minutes, created_at)
				VALUES (?, 2, '월요일', ?, ?, CURRENT_TIMESTAMP)
				""", roomId, java.sql.Time.valueOf(startAt.toLocalTime()), Math.max(20, java.time.Duration.between(startAt, endAt).toMinutes()));
		long scheduleId = jdbcTemplate.queryForObject("SELECT MAX(id) FROM reading_room_schedules", Long.class);
		jdbcTemplate.update("""
				INSERT INTO reading_room_sessions (
					room_id, schedule_id, session_date, scheduled_start_at, scheduled_end_at, started_at, ended_at, status, created_at, updated_at
				)
				VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
				""",
				roomId,
				scheduleId,
				java.sql.Date.valueOf(startAt.toLocalDate()),
				Timestamp.valueOf(startAt),
				Timestamp.valueOf(endAt),
				startAt.isAfter(LocalDateTime.now()) ? null : Timestamp.valueOf(startAt),
				endAt.isBefore(LocalDateTime.now()) ? Timestamp.valueOf(endAt) : null,
				endAt.isBefore(LocalDateTime.now()) ? "ENDED" : "SCHEDULED");
		return roomId;
	}

	private void insertParticipant(long roomId, long userId, String status) {
		jdbcTemplate.update("""
				INSERT INTO reading_room_participants (room_id, user_id, status, joined_at)
				VALUES (?, ?, ?, CURRENT_TIMESTAMP)
				""", roomId, userId, status);
	}

	private void disableServiceNotifications(long userId) {
		jdbcTemplate.update("""
				INSERT INTO user_notification_settings (
					user_id, like_notifications_enabled, report_status_notifications_enabled,
					service_notifications_enabled, created_at, updated_at
				)
				VALUES (?, TRUE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
				""", userId);
	}

	private int countNotifications(long userId, long roomId) {
		Integer count = jdbcTemplate.queryForObject("""
				SELECT COUNT(*)
				FROM user_notifications
				WHERE user_id = ?
					AND target_type = 'SERVICE'
					AND target_id = ?
				""", Integer.class, userId, roomId);
		return count == null ? 0 : count;
	}

	private int countEvents(long userId, long roomId, String notificationType) {
		Integer count = jdbcTemplate.queryForObject("""
				SELECT COUNT(*)
				FROM reading_room_notification_events
				WHERE user_id = ?
					AND room_id = ?
					AND notification_type = ?
				""", Integer.class, userId, roomId, notificationType);
		return count == null ? 0 : count;
	}
}
